pipeline {
    agent any

    environment {
        registry = 'nexus.cicd:5000'
        appname = 'flask.hello'
        appversiontag = '4.0'
        artifact = "${registry}/${appname}:${appversiontag}"
        //nexus_user = credentials('nexus-docker-snapshots')
    }
    
    tools {
        'org.jenkinsci.plugins.docker.commons.tools.DockerTool' 'Docker 18.06.0-ce'
    }
   
    options {
        //Persist artifacts and console output for the specific number of recent Pipeline runs
        buildDiscarder(logRotator(numToKeepStr: '2', artifactNumToKeepStr: '2'))
    }

    stages {
        stage('Deploy') {
            steps {
                echo 'Deploy....'
                withDockerRegistry([url: "https://${registry}", credentialsId: 'nexus-jenkins']) {
					sh "docker rm -f ${appname}.${appversiontag} || true; docker run -p 15000:5000 -d --name ${appname}.${appversiontag} ${artifact}"
                }
            }
        }
    }
}
